

# Placeholders: Game_Root, Project_Root are built into the engine


## creates config.toml and ensures placeholders exist
## operations marked with init = true are not displayed in interactive UI or GUI lists to ensure they are always run every time
##  - ensure placeholders exist: SourcePath, Region
##  - create ./config.toml on first run if missing
##  - verify {{SourcePath}} exists and is readable
## get user input for values like region and path if needed
[[operation]]
id = 0
init = true
run-all = true # rerun when using run-all to ensure config is valid
depends-on = []
script_type = "lua"
script = "{{Game_Root}}/operations/init.lua"


## validates source only files for US and EU
## validates source folders exist changed or unchanged, should be unchanged on first run
[[operation]] ## validation steps dont do anything and only depend on db file thats dynmaically selected based on placeholders
id = 1
Name = "Validate Source Game Files and Folders"
run-all = false
depends-on = [0]
script_type = "engine"
script = "validate-files"
db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
args = [
	"{{SourcePath}}",
	"--tables", "str_index:source_path,video_index:source_path,mus_index:source_path,snu_index:source_path",
	"--required-dirs", "audiostreams||Assets_1_Audio_Streams,movies||Assets_1_Video_Movies,frontend||Assets_2_Frontend,simpsons_chars||Assets_2_Characters_Simpsons,spr_hub||Map_3-00_SprHub,loc||Map_3-01_LandOfChocolate,brt||Map_3-02_BartmanBegins,eighty_bites||Map_3-03_HungryHungryHomer,tree_hugger||Map_3-04_TreeHugger,mob_rules||Map_3-05_MobRules,cheater||Map_3-06_EnterTheCheatrix,dayofthedolphins||Map_3-07_DayOfTheDolphin,colossaldonut||Map_3-08_TheColossalDonut,dayspringfieldstoodstill||Map_3-09_Invasion,bargainbin||Map_3-10_BargainBin,gamehub||Map_3-00_GameHub,neverquest||Map_3-11_NeverQuest,grand_theft_scratchy||Map_3-12_GrandTheftScratchy,medal_of_homer||Map_3-13_MedalOfHomer,bigsuperhappy||Map_3-14_BigSuperHappy,rhymes||Map_3-15_Rhymes,meetthyplayer||Map_3-16_MeetThyPlayer",
]


##
[[operation]]
id = 2
Name = "Download Required Tools"
run-all = false
depends-on = [0]
script_type = "engine"
script = "download_tools"
tools_manifest = "{{Game_Root}}/Tools.toml"
[[operation.prompts]]
type = "confirm"
Name = "force download"
message = "Force override existing downloads?"
default = false


## renames Source Game folders for clarity
## it should be possible to run without but that case is not be fully tested
[[operation]]
id = 3
Name = "Rename base folders"
run-all = true
depends-on = [0]
script_type = "engine"
script = "rename-folders"
args = ["{{SourcePath}}", "--map-db-file", "{{Game_Root}}/config/RenameMap.db"]
[[operation.onsuccess]] # when successful, update isRenamed placeholder to "isRenamed"
Name = "set isRenamed placeholder"
script_type = "lua"
script = "{{Game_Root}}/config.lua"
args = ["--group", "placeholders", "--key", "isRenamed", "--value", "isRenamed", "--type", "string"]


## creates EN folder to match language folder patterns in EU ver
## creates Global folder for non language specific audio, mostly Ambiants
[[operation]]
id = 4
Name = "Reorganize Audio Files"
run-all = true
depends-on = [0]
script_type = "lua"
script = "{{Game_Root}}/operations/SetupAudioDir.lua"
args = ["{{SourcePath}}"]
[[operation.onsuccess]] # when successful, update isRenamed placeholder to "isRenamed"
Name = "set audio_state placeholder"
script_type = "lua"
script = "{{Game_Root}}/config.lua"
args = ["--group", "placeholders", "--key", "audio_state", "--value", "audio_reorg", "--type", "string"]


## ensures all changes have been non breaking
## not technically needed, just for testing
[[operation]]
id = 5
Name = "re-Validate Source Game Files and Folders"
run-all = false
depends-on = [0]
script_type = "engine"
script = "validate-files"
db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
args = [
	"{{SourcePath}}",
	"--tables", "str_index:source_path,video_index:source_path,mus_index:source_path,snu_index:source_path",
	"--required-dirs", "audiostreams||Assets_1_Audio_Streams,movies||Assets_1_Video_Movies,frontend||Assets_2_Frontend,simpsons_chars||Assets_2_Characters_Simpsons,spr_hub||Map_3-00_SprHub,loc||Map_3-01_LandOfChocolate,brt||Map_3-02_BartmanBegins,eighty_bites||Map_3-03_HungryHungryHomer,tree_hugger||Map_3-04_TreeHugger,mob_rules||Map_3-05_MobRules,cheater||Map_3-06_EnterTheCheatrix,dayofthedolphins||Map_3-07_DayOfTheDolphin,colossaldonut||Map_3-08_TheColossalDonut,dayspringfieldstoodstill||Map_3-09_Invasion,bargainbin||Map_3-10_BargainBin,gamehub||Map_3-00_GameHub,neverquest||Map_3-11_NeverQuest,grand_theft_scratchy||Map_3-12_GrandTheftScratchy,medal_of_homer||Map_3-13_MedalOfHomer,bigsuperhappy||Map_3-14_BigSuperHappy,rhymes||Map_3-15_Rhymes,meetthyplayer||Map_3-16_MeetThyPlayer",
]

## extract all other files from the archives
## .preinstanced, .ps3, .xml, .txd, .lh2, .alb, .ctb, .dat, .graph, .rcm_b, .sbk, .bsp, .smb, .mib, .amb, .uix, .imb, .toc, .msb, .inf, .bin, .aub, .txt, files with no extension
## only .preinstanced, .txd, are used
[[operation]]
id = 6
Name = "Extract Archives (.STR)"
run-all = true
depends-on = [0,2] # depends on bms tool being downloaded
script_type = "bms"
script = "{{Game_Root}}/operations/simpsons_str.bms"
input = "{{SourcePath}}"
output = "{{Game_Root}}/GameFiles/{{STROUT}}"
extension = ".str"



## if you need proof this is needed heres the stats
#Root          : A:\RemakeEngine\EngineApps\Games\TheSimpsonsGame-PS3\GameFiles\STROUT_Normalized
#TotalItems    : 90536
#MaxPath       : A:\RemakeEngine\EngineApps\Games\TheSimpsonsGame-PS3\GameFiles\STROUT_Normalized\Map_3-12_GrandTheftScr
#                atchy\props\misc\gts_clip_joint_npccollide_placeholder_eps_grand_theft_scratchy_misc__K3ta5u5fva5gts_cl
#                ip_joint_npccollide_placeholder.meta.xml
#MaxPathLength : 246
#CountOver240  : 3
#CountOver248  : 0
#CountOver260  : 0

## Compared to original extraction
#Root          : A:\RemakeEngine\EngineApps\Games\TheSimpsonsGame-PS3\GameFiles\STROUT
#TotalItems    : 59791
#MaxPath       : A:\RemakeEngine\EngineApps\Games\TheSimpsonsGame-PS3\GameFiles\STROUT\Map_3-09_Invasion\dayspringfields
#                toodstill\story_mode\igcs\igc_02_folderstream\sss_igc02_shot04_str\build\PS3\pal_en\assets_rws\daysprin
#                gfieldstoodstill\dayspringfieldstoodstill\texture_dictionary\dayspringfieldstoodstill\story_mode\igcs\i
#                gc_02_folderstream\sss_igc02_shot04.txd
#MaxPathLength : 348
#CountOver240  : 6322
#CountOver248  : 4691
#CountOver260  : 2783
## the longest path being 348 characters long is a problem for blender and godot, mostly godot now
##
## blender cannot handle paths that exeed windows path limits
## blender refused to accept my solutions to this so i did two things to ensure it works for -
## blender and any other application that needs to handle the files
## blender is currently solved using symbolic links for assets, and \\?\ for texture paths, this (\\?\) actually working indicates the i dont need the sym links for blender and could just use \\?\ for assets as well
## the same issue also occurs in godots virtual file system, the only solution there is to flatten the folder structure
## this process specificaly reduces redundent directory structurs without removing improtant path data
#[[operation]] old C# flattener, replaced by lua normalizer
#id = 7
#Name = "flatten folder structure"
#run-all = false
#depends-on = [0]
#script_type = "engine"
#script = "flatten"
#args = ["{{SourcePath}}", "{{Game_Root}}/SourceFlat", "--rules", "{{Game_Root}}/config/PathRules.json", "--separator", "^", "--action", "copy", "--ignore", "audiostreams", "--ignore", "movies"]
[[operation]]
id = 7
Name = "Normalize folder structure"
run-all = true
depends-on = [0]
script_type = "lua"
script = "{{Game_Root}}/operations/DirectoryNormalizer.lua"
args = ["{{Game_Root}}/GameFiles/{{STROUT}}", "{{Game_Root}}/GameFiles/{{STROUT}}_Normalized", "--rules", "{{Game_Root}}/config/DirectoryNormalizer.rules.json", "--action", "copy", "--ignore", "audiostreams", "--ignore", "movies"]
[[operation.prompts]]
type = "confirm"
Name = "dry run?"
message = "dry run (no files will be copied)?"
default = false
cli_arg = "--dry-run"
[[operation.onsuccess]] # when successful, update placeholders to normalized
Name = "update normalized placeholders"
script_type = "lua"
script = "{{Game_Root}}/config.lua"
args = ["--group", "placeholders", "--set", "STROUT=STROUT_Normalized:string", "--set", "Type=FullFlattened:string"]


## extract textures from texture dictionaries that were extracted from .str files
[[operation]]
id = 8
Name = "Extract Textures (.txd -> .dds)"
run-all = true
depends-on = [0,7]
script_type = "engine"
script = "format-extract"
format = "txd"
args = ["{{Game_Root}}/GameFiles/{{STROUT}}"]

[[operation]]
id = 9
Name = "Convert Textures (.dds -> .png)"
run-all = true
depends-on = [0,7,8,2]
script_type = "engine"
script = "format-convert"
tool = "ImageMagick"
args = [
	"--source", "{{Game_Root}}/GameFiles/{{STROUT}}",
	"--target", "{{Game_Root}}/GameFiles/{{STROUT}}",
	"--input-ext", ".dds",
	"--output-ext", ".png"
]

## validate extraction of str and txd files
[[operation]]
id = 10
Name = "validate extracted game files"
run-all = false
depends-on = [0]
script_type = "engine"
script = "validate-files"
db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
args = [
	"{{Game_Root}}/GameFiles/{{STROUT}}",
	"--tables", "preinstanced_index:source_path,txd_index:source_path,dds_index:source_path,png_index:source_path",
	"--required-dirs", "audiostreams||Assets_1_Audio_Streams,movies||Assets_1_Video_Movies,frontend||Assets_2_Frontend,simpsons_chars||Assets_2_Characters_Simpsons,spr_hub||Map_3-00_SprHub,loc||Map_3-01_LandOfChocolate,brt||Map_3-02_BartmanBegins,eighty_bites||Map_3-03_HungryHungryHomer,tree_hugger||Map_3-04_TreeHugger,mob_rules||Map_3-05_MobRules,cheater||Map_3-06_EnterTheCheatrix,dayofthedolphins||Map_3-07_DayOfTheDolphin,colossaldonut||Map_3-08_TheColossalDonut,dayspringfieldstoodstill||Map_3-09_Invasion,bargainbin||Map_3-10_BargainBin,gamehub||Map_3-00_GameHub,neverquest||Map_3-11_NeverQuest,grand_theft_scratchy||Map_3-12_GrandTheftScratchy,medal_of_homer||Map_3-13_MedalOfHomer,bigsuperhappy||Map_3-14_BigSuperHappy,rhymes||Map_3-15_Rhymes,meetthyplayer||Map_3-16_MeetThyPlayer",
]

## convert 3d models into .blend files, and export to glb for godot use
## auto apply textures within blender as well, however materials will need to be manually adjusted within godot
[[operation]]
id = 11
Name = "Convert Models (.preinstanced -> .blend)"
run-all = true
depends-on = [0,2,6,8,9] # depends on blender, str extraction for assets, and texture extraction and conversion for materials
script_type = "lua"
script = "{{Game_Root}}/operations/Blender/run.lua"
args = [
	"--game-root", "{{Game_Root}}",
	"--base-dir", "{{Game_Root}}",
	"--operations-dir", "{{Game_Root}}/operations",
	"--blender-dir", "{{Game_Root}}/operations/Blender",
	"--preinstanced-dir", "{{Game_Root}}/GameFiles/{{STROUT}}",
	"--blend-dir", "{{Game_Root}}/GameFiles/{{STROUT}}",
	"--blank-blend", "{{Game_Root}}/blank.blend",
	"--root-drive", "{{Game_Root}}/TMP_TSG_LNKS",
	"--main-db", "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db",
]
# for debugging
[[operation.prompts]]
type = "confirm"
Name = "verbose"
message = "Model Conversion: Enable verbose output?"
default = false
cli_arg = "--verbose"
# for debugging
[[operation.prompts]]
type = "confirm"
Name = "debug mode"
message = "Model Conversion: Enable debug mode?"
default = false
cli_arg = "--debug-sleep"
## for direct export to glb or fbx instead of just creating .blend files
[[operation.prompts]]
type = "confirm"
Name = "enable_export"
message = "Model Conversion: Export additional formats (FBX/GLTF)?"
default = true
## for direct export to glb or fbx instead of just creating .blend files
[[operation.prompts]]
type = "checkbox"
Name = "export_formats"
message = "Select export formats:"
default = ["glb"]
choices = ["fbx", "glb"]
cli_prefix = "--export"
condition = "enable_export"
validation = { required = true, message = "You must select at least one format." }

## convert videos into a usable format for godot
[[operation]]
id = 12
Name = "Convert Videos (.vp6 -> .ogv)"
run-all = false
depends-on = [0,2] # depends on ffmpeg being downloaded
script_type = "engine"
script = "format-convert"
tool = "ffmpeg"
args = [
	"-m", "ffmpeg",
	"--type", "video",
	## doesnt need to specify the location of the movies folder as its within the source path and {{STROUT}} and the only location vp6 files exist
	"-s", "{{SourcePath}}",
	"-t", "{{Game_Root}}/GameFiles/{{STROUT}}",
	#"-f", "ffmpeg.exe",
	"-i", ".vp6",
	"-o", ".ogv"
]

## convert Audio into a usable format for godot
[[operation]]
id = 13
Name = "Convert Audio (.snu -> .wav)"
run-all = false
depends-on = [0,2] # depends on vgmstream being downloaded, could depend on audio reorg but that is technically optional
script_type = "engine"
script = "format-convert"
tool = "vgmstream"
args = [
	"-m", "vgmstream",
	"--type", "audio",
	## doesnt need to specify the location of the audiostreams folder as its within the source path and {{STROUT}} and the only location snu files exist
	"-s", "{{SourcePath}}",
	"-t", "{{Game_Root}}/GameFiles/{{STROUT}}",
	#"--vgmstream-cli", "vgmstream-cli.exe",
	"-i", ".snu",
	"-o", ".wav",
	"--godot-compatible"
]

## final validation of all files before running godot
[[operation]]
id = 14
Name = "Validate all game files"
run-all = false
depends-on = [0]
script_type = "engine"
script = "validate-files"
db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
args = [
	"{{Game_Root}}/GameFiles/{{STROUT}}",
	"--tables", "preinstanced_index:source_path,glb_index:source_path,txd_index:source_path,dds_index:source_path,png_index:source_path,audio_wav_index:source_path,video_ogv_index:source_path",
	"--required-dirs", "audiostreams||Assets_1_Audio_Streams,movies||Assets_1_Video_Movies,frontend||Assets_2_Frontend,simpsons_chars||Assets_2_Characters_Simpsons,spr_hub||Map_3-00_SprHub,loc||Map_3-01_LandOfChocolate,brt||Map_3-02_BartmanBegins,eighty_bites||Map_3-03_HungryHungryHomer,tree_hugger||Map_3-04_TreeHugger,mob_rules||Map_3-05_MobRules,cheater||Map_3-06_EnterTheCheatrix,dayofthedolphins||Map_3-07_DayOfTheDolphin,colossaldonut||Map_3-08_TheColossalDonut,dayspringfieldstoodstill||Map_3-09_Invasion,bargainbin||Map_3-10_BargainBin,gamehub||Map_3-00_GameHub,neverquest||Map_3-11_NeverQuest,grand_theft_scratchy||Map_3-12_GrandTheftScratchy,medal_of_homer||Map_3-13_MedalOfHomer,bigsuperhappy||Map_3-14_BigSuperHappy,rhymes||Map_3-15_Rhymes,meetthyplayer||Map_3-16_MeetThyPlayer",
	"--debug"
]




## the HARD part
[[operation]]
id = 15
Name = "generate Godot Game (EXPERIMENTAL)"
run-all = false
depends-on = [0,6,8,9,11,12,13,14]
script_type = "lua"
script = "{{Game_Root}}/Game/init.lua"
args = ["--project-name", "SimpsonsGamePS3", "--repo-root", "{{Project_Root}}", "--sourcePath", "{{Game_Root}}/GameFiles/{{STROUT}}"]

## the HARD part but its menus, and UI this time
[[operation]]
id = 16
Name = "GODOT - Generate Menu's (EXPERIMENTAL)"
run-all = false
depends-on = [0,6,8,9,11,12,13,14]
script_type = "lua"
script = "{{Project_Root}}/EngineApps/Games/TheSimpsonsGame-PS3/Game.Menu/init.lua"
args = ["--project-name", "SimpsonsGamePS3", "--repo-root", "{{Project_Root}}", "--sourcePath", "{{Game_Root}}/GameFiles/{{STROUT}}"]

## more HARD parts to come?...
