

# Placeholders: Game_Root, Project_Root are built into the engine

# validate-files operations cannot be run until the indexing db's are generated manually
## there could be two different indexes, a source index for us and eu thats packed with the repo,
## and a index that is generated in this after some processes just before blender so blender has a texture index to find the extracted textures
## this would mean no intermediary validation would be possible as thered be no source of truth, since creating an index of the files you have isnt validation that the output is correct but as long as the input is correct it should generally be fine


## creates config.toml and ensures placeholders exist
## operations marked with init = true are not displayed in interactive UI or GUI lists to ensure they are always run every time
##  - ensure placeholders exist: SourcePath, Region
##  - create ./config.toml on first run if missing
##  - verify {{SourcePath}}/{{Region}}/{{PostSourcePath}} exists and is readable
## get user input for values like region and path if needed
[[operation]]
id = 0
init = true
run-all = true # rerun when using run-all to ensure config is valid
depends-on = []
script_type = "lua"
script = "{{Game_Root}}/operations/init.lua"

## dev test, change region to EU or US, also change SourcePath to //US or //EU paths
[[operation]]
id = -4
Name = "change region to US"
script_type = "engine"
script = "config"
args = [
    "--group", "placeholders",
    "--set", "Region=US:string",
    "--set", "MainSourcePath={{Game_Root}}/Source/US/PS3_GAME/USRDIR:string"
]
[[operation]]
id = -2
Name = "change region to EU"
script_type = "engine"
script = "config"
args = [
    "--group", "placeholders",
    "--set", "Region=EU:string",
    "--set", "MainSourcePath={{Game_Root}}/Source/EU/PS3_GAME/USRDIR:string"
]


## validates source only files for US and EU
## validates source folders exist changed or unchanged, should be unchanged on first run
#[[operation]] ## validation steps dont do anything and only depend on db file thats dynmaically selected based on placeholders
#id = 1
#Name = "Validate Source Game Files and Folders"
#run-all = false
#depends-on = [0]
#script_type = "engine"
#script = "validate-files"
#db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
#args = [
#    "{{SourcePath}}/{{Region}}/{{PostSourcePath}}",
#    "--tables", "str_index:source_path,video_index:source_path,mus_index:source_path,snu_index:source_path",
#    "--required-dirs", "audiostreams,movies,frontend,simpsons_chars,spr_hub,loc,brt,eighty_bites,tree_hugger,mob_rules,cheater,dayofthedolphins,colossaldonut,dayspringfieldstoodstill,bargainbin,gamehub,neverquest,grand_theft_scratchy,medal_of_homer,bigsuperhappy,rhymes,meetthyplayer",
#]


##
[[operation]]
id = 2
Name = "Download Required Tools"
run-all = true
depends-on = [0]
script_type = "engine"
script = "download-tools"
tools_manifest = "{{Game_Root}}/Tools.toml"
[[operation.prompts]]
type = "confirm"
Name = "force download"
message = "Force override existing downloads?"
default = false

## ensures all changes have been non breaking
## not technically needed, just for testing
#[[operation]]
#id = 5
#Name = "re-Validate Source Game Files and Folders"
#run-all = false
#depends-on = [0]
#script_type = "engine"
#script = "validate-files"
#db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
#args = [
#    "{{SourcePath}}/{{Region}}/{{PostSourcePath}}",
#    "--tables", "str_index:source_path,video_index:source_path,mus_index:source_path,snu_index:source_path",
#    "--required-dirs", "audiostreams||A1_Audio, movies||A1_Video, frontend||A2_Frontend, simpsons_chars||A2_Characters_Simpsons, spr_hub||L00_SprHub, loc||L01_LandOfChocolate, brt||L02_BartmanBegins, eighty_bites||L03_HungryHungryHomer, tree_hugger||L04_TreeHugger, mob_rules||L05_MobRules, cheater||L06_EnterTheCheatrix, dayofthedolphins||L07_DayOfTheDolphin, colossaldonut||L08_TheColossalDonut, dayspringfieldstoodstill||L09_Invasion,bargainbin||L10_BargainBin,gamehub||L00_GameHub,neverquest||L11_NeverQuest,grand_theft_scratchy||L12_GrandTheftScratchy,medal_of_homer||L13_MedalOfHomer,bigsuperhappy||L14_BigSuperHappy,rhymes||L15_Rhymes,meetthyplayer||L16_MeetThyPlayer",
#]

## extract all other files from the archives
## .preinstanced, .ps3, .xml, .txd, .lh2, .alb, .ctb, .dat, .graph, .rcm_b, .sbk, .bsp, .smb, .mib, .amb, .uix, .imb, .toc, .msb, .inf, .bin, .aub, .txt, files with no extension
## only .preinstanced, .txd, are used
[[operation]]
id = 6
Name = "Extract Archives (.STR)"
run-all = true
depends-on = [0,2] # depends on bms tool being downloaded
script_type = "bms"
script = "{{Game_Root}}/operations/simpsons_str.bms"
input = "{{SourcePath}}/{{Region}}/{{PostSourcePath}}"
output = "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}" # always output to STROUT not {{STROUT}}
extension = ".str"

## extract textures from texture dictionaries that were extracted from .str files
[[operation]]
id = 8
Name = "Extract Textures (.txd -> .dds)"
run-all = true
depends-on = [0,7]
script_type = "engine"
script = "format-extract"
format = "txd"
args = ["{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}"]

[[operation]]
id = 9
Name = "Convert Textures (.dds -> .png)"
run-all = true
depends-on = [0,7,8,2]
script_type = "engine"
script = "format-convert"
tool = "ImageMagick"
args = [
    "--source", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "--target", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "--input-ext", ".dds",
    "--output-ext", ".png"
]


# convert all lh2 dialogue/subtitles to csv
[[operation]]
id = 17
Name = "Extract Dialogue/Subtitles (.lh2 -> .csv)"
run-all = true
depends-on = [0]
script_type = "lua"
script = "{{Game_Root}}/operations/lh2_to_csv.lua"
args = [
    "--input-dir", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}"
    # auto output to same location as input files
]



## validate extraction of str and txd files
#[[operation]]
#id = 10
#Name = "validate extracted game files"
#run-all = false
#depends-on = [0]
#script_type = "engine"
#script = "validate-files"
#db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
#args = [
#    "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
#    "--tables", "preinstanced_index:source_path,txd_index:source_path,dds_index:source_path,png_index:source_path",
#    "--required-dirs", "audiostreams||A1_Audio,movies||A1_Video,frontend||A2_Frontend,simpsons_chars||A2_Characters_Simpsons,spr_hub||L00_SprHub,loc||L01_LandOfChocolate,brt||L02_BartmanBegins,eighty_bites||L03_HungryHungryHomer,tree_hugger||L04_TreeHugger,mob_rules||L05_MobRules,cheater||L06_EnterTheCheatrix,dayofthedolphins||L07_DayOfTheDolphin,colossaldonut||L08_TheColossalDonut,dayspringfieldstoodstill||L09_Invasion,bargainbin||L10_BargainBin,gamehub||L00_GameHub,neverquest||L11_NeverQuest,grand_theft_scratchy||L12_GrandTheftScratchy,medal_of_homer||L13_MedalOfHomer,bigsuperhappy||L14_BigSuperHappy,rhymes||L15_Rhymes,meetthyplayer||L16_MeetThyPlayer",
#]

## convert 3d models into .blend files, and export to glb for godot use
## auto apply textures within blender as well, however materials will need to be manually adjusted within godot
[[operation]]
id = 11
Name = "Convert Models (.preinstanced -> .blend)"
run-all = true
depends-on = [0,2,6,8,9] # depends on blender, str extraction for assets, and texture extraction and conversion for materials
script_type = "lua"
script = "{{Game_Root}}/operations/Blender/run.lua"
args = [
    "--game-root", "{{Game_Root}}",
    "--base-dir", "{{Game_Root}}",
    "--operations-dir", "{{Game_Root}}/operations",
    "--blender-dir", "{{Game_Root}}/operations/Blender",
    "--preinstanced-dir", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "--blend-dir", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "--blank-blend", "{{Game_Root}}/blank.blend",
    "--root-drive", "{{Game_Root}}/TMP_TSG_LNKS-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}", # symbolic link root to avoid path length issues
    "--main-db", "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db",
    "--asset-map-db", "{{Game_Root}}/GameFiles/config/{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}/AssetMap.sqlite",
]
# for debugging
[[operation.prompts]]
type = "confirm"
Name = "verbose"
message = "Model Conversion: Enable verbose output?"
default = false
cli_arg = "--verbose"
# for debugging
[[operation.prompts]]
type = "confirm"
Name = "debug mode"
message = "Model Conversion: Enable debug mode?"
default = false
cli_arg = "--debug-sleep"
## for direct export to glb or fbx instead of just creating .blend files
[[operation.prompts]]
type = "confirm"
Name = "enable_export"
message = "Model Conversion: Export additional formats (FBX/GLTF)?"
default = true
## for direct export to glb or fbx instead of just creating .blend files
[[operation.prompts]]
type = "checkbox"
Name = "export_formats"
message = "Select export formats:"
default = ["glb"]
choices = ["fbx", "glb"]
cli_prefix = "--export"
condition = "enable_export"
validation = { required = true, message = "You must select at least one format." }




## convert videos into a usable format for godot
[[operation]]
id = 12
Name = "Convert Videos (.vp6 -> .ogv)"
run-all = true
depends-on = [0,2] # depends on ffmpeg being downloaded
script_type = "engine"
script = "format-convert"
tool = "ffmpeg"
args = [
    "-m", "ffmpeg",
    "--type", "video",
    ## doesnt need to specify the location of the movies folder as its within the source path and {{STROUT}} and the only location vp6 files exist
    "-s", "{{SourcePath}}/{{Region}}/{{PostSourcePath}}",
    "-t", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    #"-f", "ffmpeg.exe",
    "-i", ".vp6",
    "-o", ".ogv"
]

## convert Audio into a usable format for godot
[[operation]]
id = 13
Name = "Convert Audio (.snu -> .wav)"
run-all = true
depends-on = [0,2] # depends on vgmstream being downloaded, could depend on audio reorg but that is technically optional
script_type = "engine"
script = "format-convert"
tool = "vgmstream"
args = [
    "-m", "vgmstream",
    "--type", "audio",
    ## doesnt need to specify the location of the audiostreams folder as its within the source path and {{STROUT}} and the only location snu files exist
    "-s", "{{SourcePath}}/{{Region}}/{{PostSourcePath}}",
    "-t", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "-i", ".snu",
    "-o", ".wav",
    "--godot-compatible"
]

## creates EN folder to match language folder patterns in EU ver
## creates Global folder for non language specific audio, mostly Ambiants
[[operation]]
id = 4
Name = "Reorganize Audio Files"
run-all = true
depends-on = [0,6,13]
script_type = "lua"
script = "{{Game_Root}}/operations/SetupAudioDir.lua"
args = ["{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}"]
[[operation.onsuccess]] # when successful, update isRenamed placeholder to "isRenamed"
Name = "set audio_state placeholder"
script_type = "engine"
script = "config"
args = ["--group", "placeholders", "--key", "audio_state", "--value", "audio_reorg", "--type", "string"]
[[operation.onsuccess]]
Name = "rename folder STROUT-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}} to STROUT-{{Region}}_{{Type}}-audio_reorg-{{isRenamed}}"
script_type = "lua"
script = "{{Game_Root}}/rename.lua"
args = [
    "--old_path", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-audio_og-{{isRenamed}}",
    "--new_path", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-audio_reorg-{{isRenamed}}"
]


## renames output Game folders for clarity
[[operation]]
id = 3
Name = "Rename base folders"
run-all = true
depends-on = [0,6,12,13]
script_type = "engine"
script = "rename-folders"
args = ["{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}", "--map-db-file", "{{Game_Root}}/config/RenameMap.db"]
[[operation.onsuccess]] # when successful, update {{isRenamed}} placeholder to "isRenamed"
Name = "set isRenamed placeholder"
script_type = "engine"
script = "config"
args = ["--group", "placeholders", "--key", "isRenamed", "--value", "isRenamed", "--type", "string"]
[[operation.onsuccess]]
Name = "rename folder STROUT-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}} to STROUT-{{Region}}_{{Type}}-{{audio_state}}-isRenamed"
script_type = "lua"
script = "{{Game_Root}}/rename.lua"
args = [
    "--old_path", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-notRenamed",
    "--new_path", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-isRenamed"
]


## ignoring audio/video folder after conversion means those files wont be copied to the final game folder,
## they cant be run in the flattener as theres too many files, so they need to be copied manually or run after the flattener

## blender cannot handle paths that exeed windows path limits
## blender refused to accept my solutions to this so i did two things to ensure it works for -
## blender and any other application that needs to handle the files
## blender is currently solved using symbolic links for assets, and \\?\ for texture paths, this (\\?\) actually working indicates the i dont need the sym links for blender and could just use \\?\ for assets as well
## the same issue also occurs in godots virtual file system, the only solution there is to flatten the folder structure
## this process specificaly reduces redundent directory structurs without removing improtant path data
#[[operation]] old C# flattener, replaced by lua normalizer
#id = 7
#Name = "flatten folder structure"
#run-all = false
#depends-on = [0]
#script_type = "engine"
#script = "flatten"
#args = ["{{SourcePath}}/{{Region}}/{{PostSourcePath}}", "{{Game_Root}}/SourceFlat", "--rules", "{{Game_Root}}/config/PathRules.json", "--separator", "^", "--action", "copy", "--ignore", "audiostreams", "--ignore", "movies"]
[[operation]]
id = 7
Name = "Normalize folder structure"
run-all = true
depends-on = [0]
script_type = "lua"
script = "{{Game_Root}}/operations/DirectoryNormalizer/run.lua"
args = [
    "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}Flattened-{{audio_state}}-{{isRenamed}}",
    #"--rules", "{{Game_Root}}/config/DirectoryNormalizer.rules.json",
    #"--action", "copy",
    "--copyonly", "A1_Audio",
    "--copyonly", "A1_Video",
]
#[[operation.prompts]] Dev option
#type = "confirm"
#Name = "dry run?"
#message = "dry run (no files will be copied)?"
#default = false
#cli_arg = "--dry-run"
[[operation.onsuccess]] # when successful, update placeholders to normalized
Name = "update normalized placeholders"
script_type = "engine"
script = "config"
args = [
    "--group", "placeholders",
    "--set", "Type=FullFlattened:string"
]




## final validation of all files before running godot
#[[operation]]
#id = 14
#Name = "Validate all game files"
#run-all = false
#depends-on = [0]
#script_type = "engine"
#script = "validate-files"
#db = "{{Game_Root}}/config/GameFilesIndex_{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}.db"
#args = [
#    "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
#    "--tables", "preinstanced_index:source_path,glb_index:source_path,txd_index:source_path,dds_index:source_path,png_index:source_path,audio_wav_index:source_path,video_ogv_index:source_path",
#    "--required-dirs", "audiostreams||A1_Audio,movies||A1_Video,frontend||A2_Frontend,simpsons_chars||A2_Characters_Simpsons,spr_hub||L00_SprHub,loc||L01_LandOfChocolate,brt||L02_BartmanBegins,eighty_bites||L03_HungryHungryHomer,tree_hugger||L04_TreeHugger,mob_rules||L05_MobRules,cheater||L06_EnterTheCheatrix,dayofthedolphins||L07_DayOfTheDolphin,colossaldonut||L08_TheColossalDonut,dayspringfieldstoodstill||L09_Invasion,bargainbin||L10_BargainBin,gamehub||L00_GameHub,neverquest||L11_NeverQuest,grand_theft_scratchy||L12_GrandTheftScratchy,medal_of_homer||L13_MedalOfHomer,bigsuperhappy||L14_BigSuperHappy,rhymes||L15_Rhymes,meetthyplayer||L16_MeetThyPlayer",
#    "--debug"
#]




## the HARD part
[[operation]]
id = 15
Name = "generate Godot Game (EXPERIMENTAL)"
run-all = false
depends-on = [0,6,8,9,11,12,13,14]
script_type = "lua"
script = "{{Game_Root}}/Godot/Game/godot-init-V0.5.1.lua"
args = [
    "--project-name", "SimpsonsGamePS3",
    "--repo-root", "{{Project_Root}}",
    "--sourcePath", "{{Game_Root}}/GameFiles/{{STROUT}}-{{Region}}_{{Type}}-{{audio_state}}-{{isRenamed}}",
    "--iconPath", "{{SourcePath}}/{{Region}}/{{PostSourcePath}}",
    "--no-exit"
]
