title = "The Simpsons Game PS3 Tools"

[[tool]]
name = "Blender"
# it is possible to use 4.5.4 but this auto disables the 'auto_smooth' feature in the blender 'preinstanced import' addon as its no longer supported in 4.1+
version = "4.5.4"
# when chaning version the blank.blend file needs to be re-saved in that version
#version = "4.0.2" # this version cant handle long paths and requires symlinks
unpack = true

[[tool]]
name = "QuickBMS"
version = "0.12.0"
unpack = true

[[tool]]
name = "Godot"
version = "4.5-stable-mono"
#version = "4.6-stable-mono"
unpack = true

[[tool]]
name = "vgmstream-cli"
version = "r2023"
unpack = true

[[tool]]
name = "ffmpeg"
version = "8.0"
unpack = true

