--[[
Simplified build script for generating a static game.toml
]]

local function Fail(Message)
    sdk.color_print('red', Message)
    Diagnostics.Log('[demo-build] ERROR: ' .. Message)
    error(Message)
end

local function WriteTextFile(Path, Content)
    local Ok = sdk.write_file(Path, Content)
    if not Ok then
        Fail('Failed to write file: ' .. tostring(Path))
    end
end

local function BuildStaticGameToml()
    return table.concat({
        '# Auto-generated by EngineApps/Games/demo/scripts/build.lua',
        'title = "Godot Game Project"',
        'name = "TSG"',
        'exe = "{{Game_Root}}/Godot/GodotGame/PreBuilt/project.godot"',
        ''
    }, '\n')
end

local function Main()
    -- Resolve the root directory just like the original script
    local ModuleRoot = type(Game_Root) == 'string' and Game_Root or '.'
    local ModuleGameTomlPath = join(ModuleRoot, 'game.toml')

    progress.script.start(1, 'Generating static game.toml')
    progress.script.step('Writing file')

    -- Generate and write the TOML content
    local TomlContent = BuildStaticGameToml()
    WriteTextFile(ModuleGameTomlPath, TomlContent)

    progress.script.finish()

    sdk.color_print('green', 'game.toml successfully generated at: ' .. ModuleGameTomlPath)
end

Main()