[book]
authors = ["samarixum"]
language = "en"
src = "docs"
title = "Remake Engine Docs"
# output folder ../doc

multilingual = false
[output.html]
default-theme = "Coal"
preferred-dark-theme = "Ayu"
git-repository-url = "https://github.com/superposition28/TheSimpsonsGame-PS3"
edit-url-template = "https://github.com/superposition28/TheSimpsonsGame-PS3/edit/main/src/{path}"
